export const CAMPGROUND_SCOPE = [
    "grills",
    "drinking water",
    "water spigots",
    "water spigot",
    "campfire rings",
    "fire rings",
    "campfires",
    "picnic tables",
    "tables",
    "toilets",
    "flush toilets",
    "vault toilets",
    "showers",
    "pets",
    "pets allowed",
    "campfire allowed",
    "checkin time",
    "checkout time",
    "tent pads",
    "campfire circles",
    "recycling",
    "paved roads",
    "food storage locker",
    "accessible parking",
    "accessible campsites",
    "accessible picnic area",
    "coin showers",
    "emergency phone",
    "host",
    "campground host",
    "visitor center",
    "lake access",
    "firewood",
    "firewood vender",
    "firewood vendor",
    "campfire programs",
    "amphitheater",
    "camping supplies",
    "general store",
    "gift shop",
    "parking area",
    "restaurant",
    "accessible flush toilets",
    "accessible showers",
    "fuel",
    "gas",
    "gas station",
    "fuel available",
    "trash collection",
    "ice",
    "rv parking",
    "lantern",
    "corrals",
    "fishing licenses",
    "trailheads",
    "utility sinks",
    "smoke alarm",
    "propane",
    "laundry",
    "laundromat",
    "laundry facilities",
    "clothes dryer",
    "atm",
    "church",
    "electricity",
    "electric hookups",
    "water hookups",
]

export const CAMPSITE_SCOPE = [
    "equipment",
    "is equipment mandatory",
    "picnic table",
    "fire ring",
    "shade",
    "site access",
    "bbq",
    "grill",
    "capacity/size rating",
    "driveway entry",
    "driveway grade",
    "driveway surface",
    "driveway length",
    "fire pit",
    "max num of people",
    "max num of vehicles",
    "max vehicle length",
    "min num of people",
    "min num of vehicles",
    "map x coordinate",
    "map y coordinate",
    "placed on map",
    "hike in distance to site",
    "tent pad length",
    "tent pad width",
    "double driveway",
    "accessibility",
    "accessible occupant message",
    "privacy",
    "quiet area",
    "site height/overhead clearance",
    "site rating",
    "food locker",
    "location rating",
    "condition rating",
    "water hookup",
    "site length",
    "site width",
    "max num of horses",
    "electricity hookup",
    "bed type",
    "beds with mattress",
    "bed s with mattress",
    "bed(s) with mattress",
    "num of beds",
    "sewer hookup"
]

export function normalizeName(name: string): string {
    return name
        .trim()
        .toLowerCase()
        .replace(/_/g, " ")
        .replace(/\s+/g, " ");
}

export function getAttributeScope(attributeName: string): 'campground' | 'campsite' | 'unknown' {
    const normalized = normalizeName(attributeName);
    if(CAMPGROUND_SCOPE.includes(normalized)) return 'campground';
    if(CAMPSITE_SCOPE.includes(normalized)) return 'campsite';
    return 'unknown';
}